<?php

/* this contains name value pairs for the psudo database

accepts_postal_mail TRUE
admin_status FALSE
birth_date 05021961
cat_id 129
dir_member 100
dir_member_opt_in TRUE
districts.cong_dist 25
districts.state_house_dist 49
districts.state_senate_dist 14
email.accepts_email TRUE
email.preferred_format HTML
email.primary_address chris@luther.net
email.status verified
email_opt_in_status TRUE
employment.employer AgileID
employment.occupation Consultant
gender M
home_phone 512-442-2115
member_id 1214
membership.expiration_date 12302009
membership.id 34123
membership.last_renewal_date 12032008
membership.since_date 12032008
membership.status CURRENT
membership_level_id BASE
mobile_phone 512-636-4240
name.first Christopher
name.last Luther
name.middle D.
name.prof_suffix 
name.suffix 
name.title Mr.
origin_src_code 1242
origin_subsrc_code 1231
preferred_address home
preferred_phone mobile
primary_address.city Austin
primary_address.country Travis
primary_address.state Texas
primary_address.street1 4415 Diane Dr.
primary_address.street2 
primary_address.zip 78745
sustained_gift.card_expiration_date 12302009

*/